Base: # The `Base` is shared by different expid settings
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    patience: 2
    pickle_feature_encoder: True
    use_hdf5: True
    save_best_only: True
    every_x_epochs: 1
    debug: False
    partition_block_size: -1
    dataset_id: taobao_tiny
    gpu: 0

DNN_base_avazu:
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_h5
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DNN
    model_id: DNN_base
    model_root: ./Avazu/DNN_base_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3

DNN_fft_avazu:
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_h5
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DNN
    model_id: DNN_base
    model_root: ./Avazu/DNN_fft_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
    alpha_fft: 1
    fft_layers: 3

DNN_pool_avazu:
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_h5
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DNN
    model_id: DNN_base
    model_root: ./Avazu/DNN_pool_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
    num_cluster: 10
    pool_mlp_layers: 2
    pool_attention_layers: 2

DNN_base_criteo:
    batch_norm: false
    batch_size: 10000
    dataset_id: criteo_x4_h5
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000, 1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DNN
    model_id: DNN_base
    model_root: ./Criteo/DNN_base_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3

DNN_fft_criteo:
    batch_norm: false
    batch_size: 10000
    dataset_id: criteo_x4_h5
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000, 1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DNN
    model_id: DNN_base
    model_root: ./Criteo/DNN_fft_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
    alpha_fft: 1
    fft_layers: 3


AutoInt_base:
    model: AutoInt
    dataset_id: taobao_tiny
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10
    embedding_dim: 40
    dnn_hidden_units: [400, 400]
    dnn_activations: relu
    net_dropout: 0
    num_heads: 2
    attention_layers: 3
    attention_dim: 40
    use_residual: True
    batch_norm: False
    layer_norm: False
    use_scale: False
    use_wide: False
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

AutoInt_base_criteo:
    dataset_id: criteo_x4_h5
    attention_dim: 64
    attention_layers: 5
    batch_norm: false
    batch_size: 10000
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [1000, 1000, 1000, 1000, 1000]
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Criteo/AutoInt_base_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: false
    use_wide: true
    verbose: 1
    workers: 3

AutoInt_fft_criteo:
    dataset_id: criteo_x4_h5
    attention_dim: 64
    attention_layers: 5
    batch_norm: false
    batch_size: 10000
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [1000, 1000, 1000, 1000, 1000]
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Criteo/AutoInt_fft_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: false
    use_wide: true
    verbose: 1
    workers: 3
    alpha_fft: 1
    fft_layers: 3

AutoInt_base_avazu:
    dataset_id: avazu_x4_h5
    attention_dim: 128
    attention_layers: 7
    batch_norm: false
    batch_size: 10000
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-07
    epochs: 100
    every_x_epochs: 1
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Avazu/AutoInt_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: false
    use_scale: false
    use_wide: true
    verbose: 1
    workers: 3

AutoInt_fft_avazu:
    dataset_id: avazu_x4_h5
    attention_dim: 128
    attention_layers: 7
    batch_norm: false
    batch_size: 10000
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-07
    epochs: 100
    every_x_epochs: 1
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Avazu/AutoInt_fft_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: false
    use_scale: false
    use_wide: true
    verbose: 1
    workers: 3
    alpha_fft: 1
    fft_layers: 3

