Base: # The `Base` is shared by different expid settings
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    patience: 2
    pickle_feature_encoder: True
    use_hdf5: True
    save_best_only: True
    every_x_epochs: 1
    debug: False
    partition_block_size: -1
    dataset_id: taobao_tiny
    gpu: 0



AutoInt_base_criteo:
    attention_dim: 64
    attention_layers: 5
    batch_norm: false
    batch_size: 10000
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [1000, 1000, 1000]
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Criteo/AutoInt_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: false
    use_wide: true
    verbose: 0
    workers: 3

AutoInt_fft_criteo:
    attention_dim: 64
    attention_layers: 5
    batch_norm: false
    batch_size: 10000
    dataset_id: criteo_x4
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [1000, 1000, 1000]
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AutoInt_fft
    model_id: AutoInt_fft
    model_root: ./Criteo/AutoInt_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: false
    use_wide: true
    verbose: 0
    workers: 3
    alpha_fft: 1

AutoInt_base_avazu:
    attention_dim: 128
    attention_layers: 7
    batch_norm: false
    batch_size: 10000
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-07
    epochs: 100
    every_x_epochs: 1
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Avazu/AutoInt_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: false
    use_scale: false
    use_wide: true
    verbose: 0
    workers: 3

AutoInt_fft_avazu:
    attention_dim: 128
    attention_layers: 7
    batch_norm: false
    batch_size: 10000
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-07
    epochs: 100
    every_x_epochs: 1
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Avazu/AutoInt_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: false
    use_scale: false
    use_wide: true
    verbose: 0
    workers: 3
    alpha_fft: 1


DCN_base_criteo:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 4
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [1000, 1000, 1000, 1000, 1000]
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
    workers: 3


DCN_fft_criteo:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 4
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [1000, 1000, 1000, 1000, 1000]
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN_fft
    model_id: DCN_fft
    model_root: ./Criteo/DCN_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
    workers: 3
    alpha_fft: 1


DCN_base_avazu:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 3
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [2000, 2000, 2000]
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Avazu/DCN_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
    workers: 3

DCN_fft_avazu:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 3
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [2000, 2000, 2000]
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Avazu/DCN_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
    workers: 3
    alpha_fft: 1s